apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tmp"
  annotations:
    github.com/project-slug: 'kk-rishang/tmp'
spec:
  type: service
  owner: user:kk-rishang
  lifecycle: experimental
